services:
  #OLLAMA
  ollama:
      # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER:-nvidia}
              count: ${OLLAMA_GPU_COUNT:-1}
              capabilities:
                - gpu
        limits:
          memory: ${OLLAMA_MEM_MAX:-8GB}
