services:
  #OLLAMA
  ollama:
    image: "darahsan/ollama-s6"
    container_name: ollama
    cpu_shares: 64
    environment:
      - LLM_MODEL=${OLLAMA_LLM_MODEL:-nomic-embed-text,qwen2:1.5b,deepseel-r1:1.5b,smoollm2}
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASHH_ATTENTION:-1}
      - OLLAMA_KV_CACHE_TYPE=${OLLAMMA_KV_CACHE_TYPE:-q4_0}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-4}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-2}
    volumes:
      - "ollama-data:/root/.ollama"
    ports:
      - "11434:11434"
    mem_reservation: ${OLLAMA_MEM_MIN:-4G}
    restart: unless-stopped

  #OLLAMA-WEBUI 
  ollama-webui:
    image: "ghcr.io/open-webui/open-webui:main"
    container_name: ollama-webui
    volumes:
        - ollama-webui-data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
  
volumes:
  ollama-data: {}
  ollama-webui-data: {}

